[package]
name = "tmpl"
version = "0.1.0"
edition = "2021"

[dependencies]
client = { path = "../../../rust/lib/client" }
prost = "0.12.6"

[build-dependencies]
aok = "0.1.12"
prost-build = "0.12.6"

[package.metadata.cargo-machete]
ignored = ["prost"]
